dist: xenial

group: travis_lts

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions

language: python


jdk:
   - openjdk8

matrix:
  include:
    - python: 3.8
      arch: arm64
      env: PIP_PYSPARK=3.1.2 SKLEARN_VERSION="0.23.1"
    - python: 3.7
      env: PIP_PYSPARK="pyspark==3.0.1" SKLEARN_VERSION="0.21.3"
    - python: 3.7
      env: PIP_PYSPARK="pyspark==2.4.5" SKLEARN_VERSION="0.21.3" JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"

install:
  - pip install joblib==0.14.0 scikit-learn==${SKLEARN_VERSION} nose==1.3.3 pytest pylint;
  - pip install ${PIP_PYSPARK}

script:
  - PYSPARK_PYTHON=python ./run-tests.sh

